// Generated by CoffeeScript 1.7.1
(function() {
  console.log($('button'));

  $('#bewarebutton').click(function(event) {
    return $('h1').append(" " + "B00!!!");
  });

  $('#trick').click(function(event) {
    var counter;
    counter = $('#counter').html();
    counter = parseInt(counter);
    $('#counter').html(counter + 1);
    return console.log(counter = counter + 1);
  });

  $('#reset2').click(function(event) {
    var counter;
    counter = $('#counter').html();
    counter = parseInt(counter);
    return $('#counter').html(counter - counter);
  });

}).call(this);
